# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

# HopliteLabs.Result\HopliteLabs.Result.Core\bin\Release\HopliteLabs.Result.Core.1.0.0.nupkg

# HopliteLabs.Result/HopliteLabs.Result.Core/bin/Release/HopliteLabs.Result.Core.${{ env.VERSION }}.nupkg

name: .NET

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    defaults:
      run:
        working-directory: ./src

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Get version
        run: echo "VERSION=$(echo ${{ github.ref_name }} | tr -d v)" >> $GITHUB_ENV
      - name: Restore dependencies
        run: dotnet restore ./HopliteLabs.Result
      - name: Build
        run: dotnet build -c release --no-restore ./HopliteLabs.Result
      - name: Test
        run: dotnet test -c release --no-build ./HopliteLabs.Result
      - name: Pack
        run: dotnet pack --no-build ./HopliteLabs.Result /p:Version=${{ env.VERSION }}
      - name:
        run: dotnet nuget push ./HopliteLabs.Result/HopliteLabs.Result.Core/bin/Release/HopliteLabs.Result.Core.${{ env.VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
