# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    defaults:
      run:
        working-directory: ./src

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore ./HopliteLabs.Result
      - name: Build
        run: dotnet build -c release --no-restore ./HopliteLabs.Result
      - name: Test
        run: dotnet test ./HopliteLabs.Result
      - name: Pack
        run: dotnet pack --no-build ./HopliteLabs.Result
